# Dependencies
markdown:         kramdown
kramdown:
  input: GFM 

highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Yang Blog'
tagline:          'Blog On Jekyll'
description:      ''
url:              https://diego1109.github.io
baseurl:          /

author:
  name:           'yang'
  url:            https://github.com/diego1109
  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/diego1109

plugins: 
  - jekyll-seo-tag
  - jekyll-paginate
